CC = g++
CFLAGS = -Wall -Wextra -O0 -g

# all: main.cpp child1.cpp child2.cpp
# 	$(CC) $(CFLAGS) -o main main.cpp
# 	$(CC) $(CFLAGS) -o child1 child1.cpp
# 	$(CC) $(CFLAGS) -o child2 child2.cpp
all: main.cpp
	$(CC) $(CFLAGS) -o main main.cpp
	$(CC) $(CFLAGS) -o test test.cpp

